# Generated by Django 2.2.7 on 2020-08-21 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_instantmessagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstantMessageModel',
        ),
    ]
