# Generated by Django 2.2.7 on 2020-09-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_devicetypes_oss'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='current_money',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='service_usable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='spent_money',
            field=models.FloatField(default=0),
        ),
    ]
