# Generated by Django 2.2.7 on 2020-09-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_auto_20200919_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True)),
                ('deposit_date', models.DateTimeField(blank=True)),
                ('mode', models.IntegerField(blank=True, default=0)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('tracking_number', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
