# Generated by Django 2.2.7 on 2020-09-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='cost',
        ),
        migrations.AddField(
            model_name='services',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='services',
            name='parentid',
            field=models.IntegerField(default=0),
        ),
    ]
