# Generated by Django 2.2.7 on 2020-09-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20200923_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_comb', models.CharField(blank=True, max_length=255)),
                ('price', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
