# Generated by Django 2.2.7 on 2020-09-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='service_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
