# Generated by Django 2.2.7 on 2020-09-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_services_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, default=0)),
                ('service_id', models.IntegerField(blank=True, default=0)),
                ('price', models.FloatField(default=0)),
                ('pay_status', models.IntegerField(default=0)),
                ('service_status', models.IntegerField(default=0)),
                ('paid_price', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_paid', models.DateTimeField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('review', models.TextField(blank=True)),
                ('score', models.FloatField(default=0)),
            ],
        ),
    ]
