# Generated by Django 2.2.7 on 2020-09-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='category_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
