# Generated by Django 2.2.7 on 2020-09-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_orders_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
