# Generated by Django 2.2.7 on 2020-09-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_orders_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
