# Generated by Django 2.2.7 on 2020-10-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0014_auto_20200927_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_response',
            field=models.TextField(blank=True),
        ),
    ]
