# Generated by Django 2.2.7 on 2020-10-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_orders_user_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_created',
            field=models.DateTimeField(blank=True),
        ),
    ]
