# Generated by Django 2.2.7 on 2020-10-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0016_auto_20201014_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
