# Generated by Django 2.2.7 on 2020-10-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0017_auto_20201014_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='off_days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, default=0)),
                ('off_day', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='booked',
            field=models.IntegerField(default=0),
        ),
    ]
