# Generated by Django 2.2.7 on 2020-10-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0018_auto_20201014_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='booked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
