# Generated by Django 2.2.7 on 2020-10-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0019_orders_booked_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='booked_date',
            new_name='date_booked',
        ),
    ]
